#!/usr/bin/env python3
import sqlite3
conn = sqlite3.connect('data/market_data.db')
c = conn.cursor()
c.execute("SELECT name FROM sqlite_master WHERE type='table'")
print('Tables:', [r[0] for r in c.fetchall()])
c.execute('SELECT COUNT(*) FROM raw_data')
print('Raw data rows:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM clean_data')
print('Clean data rows:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM source_health')
print('Source health rows:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM notification_log')
print('Notification log rows:', c.fetchone()[0])
conn.close()
